### ISSUE TITLE
Compatibility issue with Buffer

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardBrowserExtension#41]
https://chrome.google.com/webstore/detail/buffer/noojglkidnpfjbincgijbaiedldjfbhh?hl=en
Adg on - http://imgur.com/eiLKtDj
Adg off - http://imgur.com/bUql23Z
Reproduced both on Mac&Win.
POG-728-35527

**Comment by ameshkov** [comment]
Huh, weird, thank you!

**Comment by ameshkov** [comment]
@Alex-302 could you please take a look first? Could it be filtering issue?

**Comment by Alex-302** [comment]
Yes. Too much filtered by social filter. I will fix it.

**Comment by Alex-302** [comment]
Fixed.
```
buffer.com#@#.social
buffer.com#@##sharer
```

**Comment by ameshkov** [comment]
@Alex-302 it seems this issue still exists in Safari extensions:
https://twitter.com/kylejamesfrazer/status/718499367334887426

Could you please take a look? Maybe we just add ```@@||buffer.com^$elemhide``` to Safari filter?

**Comment by Alex-302** [comment]
@ameshkov 
it caused by social rule only with Safari extension:
```~buffer.com###sharer``` 
exclusion doesn't works``` buffer.com#@##sharer```
Added ```@@||buffer.com^$elemhide``` to Safari filter

**Comment by ameshkov** [comment]
Any idea why buffer.com#@##sharer does not work?

Does it work in general?
